In [1]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import preprocessing

In [2]:
df = pd.read_csv('./data/pokemon.csv')

In [3]:
df

Number        Name   Type_1  Type_2  Total   HP  Attack  Defense  Sp_Atk  \
0         1   Bulbasaur    Grass  Poison    318   45      49       49      65   
1         2     Ivysaur    Grass  Poison    405   60      62       63      80   
2         3    Venusaur    Grass  Poison    525   80      82       83     100   
3         4  Charmander     Fire     NaN    309   39      52       43      60   
4         5  Charmeleon     Fire     NaN    405   58      64       58      80   
..      ...         ...      ...     ...    ...  ...     ...      ...     ...   
716     717     Yveltal     Dark  Flying    680  126     131       95     131   
717     718     Zygarde   Dragon  Ground    600  108     100      121      81   
718     719     Diancie     Rock   Fairy    600   50     100      150     100   
719     720       Hoopa  Psychic   Ghost    600   80     110       60     150   
720     721   Volcanion     Fire   Water    600   80     110      120     130   

     Sp_Def  ...   Color  hasGender  Pr_Male   Egg_Group_1  Egg_Group_2  \
0        65  ...   Green       True    0.875       Monster        Grass   
1        80  ...   Green       True    0.875       Monster        Grass   
2       100  ...   Green       True    0.875       Monster        Grass   
3        50  ...     Red       True    0.875       Monster       Dragon   
4        65  ...     Red       True    0.875       Monster       Dragon   
..      ...  ...     ...        ...      ...           ...          ...   
716      98  ...     Red      False      NaN  Undiscovered          NaN   
717      95  ...   Green      False      NaN  Undiscovered          NaN   
718     150  ...    Pink      False      NaN  Undiscovered          NaN   
719     130  ...  Purple      False      NaN  Undiscovered          NaN   
720      90  ...   Brown      False      NaN  Undiscovered          NaN   

     hasMegaEvolution Height_m Weight_kg  Catch_Rate       Body_Style  
0               False     0.71       6.9          45        quadruped  
1               False     0.99      13.0          45        quadruped  
2                True     2.01     100.0          45        quadruped  
3               False     0.61       8.5          45   bipedal_tailed  
4               False     1.09      19.0          45   bipedal_tailed  
..                ...      ...       ...         ...              ...  
716             False     5.79     203.0          45        two_wings  
717             False     5.00     305.0           3  serpentine_body  
718              True     0.71       8.8           3        head_arms  
719             False     0.51       9.0           3        head_only  
720             False     1.70     195.0           3        quadruped  

[721 rows x 23 columns]

In [4]:
df = df[['isLegendary','Generation', 'Type_1', 'Type_2', 'HP', 'Attack', 'Defense', 'Sp_Atk', 'Sp_Def', 'Speed','Color','Egg_Group_1','Height_m','Weight_kg','Body_Style']]

In [5]:
df

isLegendary  Generation   Type_1  Type_2   HP  Attack  Defense  Sp_Atk  \
0          False           1    Grass  Poison   45      49       49      65   
1          False           1    Grass  Poison   60      62       63      80   
2          False           1    Grass  Poison   80      82       83     100   
3          False           1     Fire     NaN   39      52       43      60   
4          False           1     Fire     NaN   58      64       58      80   
..           ...         ...      ...     ...  ...     ...      ...     ...   
716         True           6     Dark  Flying  126     131       95     131   
717         True           6   Dragon  Ground  108     100      121      81   
718         True           6     Rock   Fairy   50     100      150     100   
719         True           6  Psychic   Ghost   80     110       60     150   
720         True           6     Fire   Water   80     110      120     130   

     Sp_Def  Speed   Color   Egg_Group_1  Height_m  Weight_kg       Body_Style  
0        65     45   Green       Monster      0.71        6.9        quadruped  
1        80     60   Green       Monster      0.99       13.0        quadruped  
2       100     80   Green       Monster      2.01      100.0        quadruped  
3        50     65     Red       Monster      0.61        8.5   bipedal_tailed  
4        65     80     Red       Monster      1.09       19.0   bipedal_tailed  
..      ...    ...     ...           ...       ...        ...              ...  
716      98     99     Red  Undiscovered      5.79      203.0        two_wings  
717      95     95   Green  Undiscovered      5.00      305.0  serpentine_body  
718     150     50    Pink  Undiscovered      0.71        8.8        head_arms  
719     130     70  Purple  Undiscovered      0.51        9.0        head_only  
720      90     70   Brown  Undiscovered      1.70      195.0        quadruped  

[721 rows x 15 columns]

In [6]:
df['isLegendary'] = df['isLegendary'].astype(int)

In [7]:
df

isLegendary  Generation   Type_1  Type_2   HP  Attack  Defense  Sp_Atk  \
0              0           1    Grass  Poison   45      49       49      65   
1              0           1    Grass  Poison   60      62       63      80   
2              0           1    Grass  Poison   80      82       83     100   
3              0           1     Fire     NaN   39      52       43      60   
4              0           1     Fire     NaN   58      64       58      80   
..           ...         ...      ...     ...  ...     ...      ...     ...   
716            1           6     Dark  Flying  126     131       95     131   
717            1           6   Dragon  Ground  108     100      121      81   
718            1           6     Rock   Fairy   50     100      150     100   
719            1           6  Psychic   Ghost   80     110       60     150   
720            1           6     Fire   Water   80     110      120     130   

     Sp_Def  Speed   Color   Egg_Group_1  Height_m  Weight_kg       Body_Style  
0        65     45   Green       Monster      0.71        6.9        quadruped  
1        80     60   Green       Monster      0.99       13.0        quadruped  
2       100     80   Green       Monster      2.01      100.0        quadruped  
3        50     65     Red       Monster      0.61        8.5   bipedal_tailed  
4        65     80     Red       Monster      1.09       19.0   bipedal_tailed  
..      ...    ...     ...           ...       ...        ...              ...  
716      98     99     Red  Undiscovered      5.79      203.0        two_wings  
717      95     95   Green  Undiscovered      5.00      305.0  serpentine_body  
718     150     50    Pink  Undiscovered      0.71        8.8        head_arms  
719     130     70  Purple  Undiscovered      0.51        9.0        head_only  
720      90     70   Brown  Undiscovered      1.70      195.0        quadruped  

[721 rows x 15 columns]

In [8]:
def dummy_creation(df, dummy_categories):
    for i in dummy_categories:
        df_dummy = pd.get_dummies(df[i])
        df = pd.concat([df,df_dummy],axis=1)
        df = df.drop(i, axis=1)
    return(df)

In [9]:
df = dummy_creation(df, ['Egg_Group_1', 'Body_Style', 'Color','Type_1', 'Type_2'])

In [10]:
df

isLegendary  Generation   HP  Attack  Defense  Sp_Atk  Sp_Def  Speed  \
0              0           1   45      49       49      65      65     45   
1              0           1   60      62       63      80      80     60   
2              0           1   80      82       83     100     100     80   
3              0           1   39      52       43      60      50     65   
4              0           1   58      64       58      80      65     80   
..           ...         ...  ...     ...      ...     ...     ...    ...   
716            1           6  126     131       95     131      98     99   
717            1           6  108     100      121      81      95     95   
718            1           6   50     100      150     100     150     50   
719            1           6   80     110       60     150     130     70   
720            1           6   80     110      120     130      90     70   

     Height_m  Weight_kg  ...  Ghost  Grass  Ground  Ice  Normal  Poison  \
0        0.71        6.9  ...      0      0       0    0       0       1   
1        0.99       13.0  ...      0      0       0    0       0       1   
2        2.01      100.0  ...      0      0       0    0       0       1   
3        0.61        8.5  ...      0      0       0    0       0       0   
4        1.09       19.0  ...      0      0       0    0       0       0   
..        ...        ...  ...    ...    ...     ...  ...     ...     ...   
716      5.79      203.0  ...      0      0       0    0       0       0   
717      5.00      305.0  ...      0      0       1    0       0       0   
718      0.71        8.8  ...      0      0       0    0       0       0   
719      0.51        9.0  ...      1      0       0    0       0       0   
720      1.70      195.0  ...      0      0       0    0       0       0   

     Psychic  Rock  Steel  Water  
0          0     0      0      0  
1          0     0      0      0  
2          0     0      0      0  
3          0     0      0      0  
4          0     0      0      0  
..       ...   ...    ...    ...  
716        0     0      0      0  
717        0     0      0      0  
718        0     0      0      0  
719        0     0      0      0  
720        0     0      0      1  

[721 rows x 85 columns]

In [11]:
def train_test_splitter(DataFrame, column):
    df_train = DataFrame.loc[df[column] != 1]
    df_test = DataFrame.loc[df[column] == 1]

    df_train = df_train.drop(column, axis=1)
    df_test = df_test.drop(column, axis=1)

    return(df_train, df_test)

df_train, df_test = train_test_splitter(df, 'Generation')

In [12]:
df_test

isLegendary   HP  Attack  Defense  Sp_Atk  Sp_Def  Speed  Height_m  \
0              0   45      49       49      65      65     45      0.71   
1              0   60      62       63      80      80     60      0.99   
2              0   80      82       83     100     100     80      2.01   
3              0   39      52       43      60      50     65      0.61   
4              0   58      64       58      80      65     80      1.09   
..           ...  ...     ...      ...     ...     ...    ...       ...   
146            0   41      64       45      50      50     50      1.80   
147            0   61      84       65      70      70     70      3.99   
148            0   91     134       95     100     100     80      2.21   
149            1  106     110       90     154      90    130      2.01   
150            1  100     100      100     100     100    100      0.41   

     Weight_kg  Amorphous  ...  Ghost  Grass  Ground  Ice  Normal  Poison  \
0          6.9          0  ...      0      0       0    0       0       1   
1         13.0          0  ...      0      0       0    0       0       1   
2        100.0          0  ...      0      0       0    0       0       1   
3          8.5          0  ...      0      0       0    0       0       0   
4         19.0          0  ...      0      0       0    0       0       0   
..         ...        ...  ...    ...    ...     ...  ...     ...     ...   
146        3.3          0  ...      0      0       0    0       0       0   
147       16.5          0  ...      0      0       0    0       0       0   
148      210.0          0  ...      0      0       0    0       0       0   
149      122.0          0  ...      0      0       0    0       0       0   
150        4.0          0  ...      0      0       0    0       0       0   

     Psychic  Rock  Steel  Water  
0          0     0      0      0  
1          0     0      0      0  
2          0     0      0      0  
3          0     0      0      0  
4          0     0      0      0  
..       ...   ...    ...    ...  
146        0     0      0      0  
147        0     0      0      0  
148        0     0      0      0  
149        0     0      0      0  
150        0     0      0      0  

[151 rows x 84 columns]

In [13]:
df_train

isLegendary   HP  Attack  Defense  Sp_Atk  Sp_Def  Speed  Height_m  \
151            0   45      49       65      49      65     45      0.89   
152            0   60      62       80      63      80     60      1.19   
153            0   80      82      100      83     100     80      1.80   
154            0   39      52       43      60      50     65      0.51   
155            0   58      64       58      80      65     80      0.89   
..           ...  ...     ...      ...     ...     ...    ...       ...   
716            1  126     131       95     131      98     99      5.79   
717            1  108     100      121      81      95     95      5.00   
718            1   50     100      150     100     150     50      0.71   
719            1   80     110       60     150     130     70      0.51   
720            1   80     110      120     130      90     70      1.70   

     Weight_kg  Amorphous  ...  Ghost  Grass  Ground  Ice  Normal  Poison  \
151        6.4          0  ...      0      0       0    0       0       0   
152       15.8          0  ...      0      0       0    0       0       0   
153      100.5          0  ...      0      0       0    0       0       0   
154        7.9          0  ...      0      0       0    0       0       0   
155       19.0          0  ...      0      0       0    0       0       0   
..         ...        ...  ...    ...    ...     ...  ...     ...     ...   
716      203.0          0  ...      0      0       0    0       0       0   
717      305.0          0  ...      0      0       1    0       0       0   
718        8.8          0  ...      0      0       0    0       0       0   
719        9.0          0  ...      1      0       0    0       0       0   
720      195.0          0  ...      0      0       0    0       0       0   

     Psychic  Rock  Steel  Water  
151        0     0      0      0  
152        0     0      0      0  
153        0     0      0      0  
154        0     0      0      0  
155        0     0      0      0  
..       ...   ...    ...    ...  
716        0     0      0      0  
717        0     0      0      0  
718        0     0      0      0  
719        0     0      0      0  
720        0     0      0      1  

[570 rows x 84 columns]

In [14]:
def label_delineator(df_train, df_test, label):
    
    train_data = df_train.drop(label, axis=1).values
    train_labels = df_train[label].values
    test_data = df_test.drop(label,axis=1).values
    test_labels = df_test[label].values
    return(train_data, train_labels, test_data, test_labels)

In [15]:
train_data, train_labels, test_data, test_labels = label_delineator(df_train, df_test, 'isLegendary')

In [16]:
train_data

array([[ 45.,  49.,  65., ...,   0.,   0.,   0.],
       [ 60.,  62.,  80., ...,   0.,   0.,   0.],
       [ 80.,  82., 100., ...,   0.,   0.,   0.],
       ...,
       [ 50., 100., 150., ...,   0.,   0.,   0.],
       [ 80., 110.,  60., ...,   0.,   0.,   0.],
       [ 80., 110., 120., ...,   0.,   0.,   1.]])

In [17]:
train_labels

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [18]:
test_data

array([[ 45.,  49.,  49., ...,   0.,   0.,   0.],
       [ 60.,  62.,  63., ...,   0.,   0.,   0.],
       [ 80.,  82.,  83., ...,   0.,   0.,   0.],
       ...,
       [ 91., 134.,  95., ...,   0.,   0.,   0.],
       [106., 110.,  90., ...,   0.,   0.,   0.],
       [100., 100., 100., ...,   0.,   0.,   0.]])

In [19]:
test_labels

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1])

In [20]:
def data_normalizer(train_data, test_data):
    train_data = preprocessing.MinMaxScaler().fit_transform(train_data)
    test_data = preprocessing.MinMaxScaler().fit_transform(test_data)
    return(train_data, test_data)

train_data, test_data = data_normalizer(train_data, test_data)

In [21]:
train_data

array([[0.17322835, 0.275     , 0.26666667, ..., 0.        , 0.        ,
        0.        ],
       [0.23228346, 0.35625   , 0.33333333, ..., 0.        , 0.        ,
        0.        ],
       [0.31102362, 0.48125   , 0.42222222, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.19291339, 0.59375   , 0.64444444, ..., 0.        , 0.        ,
        0.        ],
       [0.31102362, 0.65625   , 0.24444444, ..., 0.        , 0.        ,
        0.        ],
       [0.31102362, 0.65625   , 0.51111111, ..., 0.        , 0.        ,
        1.        ]])

In [22]:
test_data

array([[0.14583333, 0.34108527, 0.25142857, ..., 0.        , 0.        ,
        0.        ],
       [0.20833333, 0.44186047, 0.33142857, ..., 0.        , 0.        ,
        0.        ],
       [0.29166667, 0.59689922, 0.44571429, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.3375    , 1.        , 0.51428571, ..., 0.        , 0.        ,
        0.        ],
       [0.4       , 0.81395349, 0.48571429, ..., 0.        , 0.        ,
        0.        ],
       [0.375     , 0.73643411, 0.54285714, ..., 0.        , 0.        ,
        0.        ]])

In [23]:
length = train_data.shape[1]

model = keras.Sequential()
model.add(keras.layers.Dense(500, activation='relu', input_shape=[length,]))
model.add(keras.layers.Dense(2, activation='softmax'))

In [24]:
model.compile(optimizer='sgd', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [25]:
model.fit(train_data, train_labels, epochs=400)

Epoch 1/400
18/18 [==============================] - 0s 2ms/step - loss: 0.6253 - accuracy: 0.7333
Epoch 2/400
18/18 [==============================] - 0s 2ms/step - loss: 0.4598 - accuracy: 0.9263
Epoch 3/400
18/18 [==============================] - 0s 4ms/step - loss: 0.3788 - accuracy: 0.9263
Epoch 4/400
18/18 [==============================] - 0s 4ms/step - loss: 0.3345 - accuracy: 0.9263
Epoch 5/400
18/18 [==============================] - 0s 3ms/step - loss: 0.3078 - accuracy: 0.9263
Epoch 6/400
18/18 [==============================] - 0s 4ms/step - loss: 0.2907 - accuracy: 0.9263
Epoch 7/400
18/18 [==============================] - 0s 4ms/step - loss: 0.2785 - accuracy: 0.9263
Epoch 8/400
18/18 [==============================] - 0s 2ms/step - loss: 0.2692 - accuracy: 0.9263
Epoch 9/400
18/18 [==============================] - 0s 3ms/step - loss: 0.2617 - accuracy: 0.9263
Epoch 10/400
18/18 [==============================] - 0s 6ms/step - loss: 0.2555 - accuracy: 0.9263
Epoch 11/

In [26]:
loss_value, accuracy_value = model.evaluate(test_data, test_labels)
print(f'Our test accuracy was {accuracy_value}')

5/5 [==============================] - 0s 3ms/step - loss: 0.0215 - accuracy: 0.9868
Our test accuracy was 0.9867549538612366


In [27]:
def predictor(test_data, test_labels, index):
    prediction = model.predict(test_data)
    if np.argmax(prediction[index]) == test_labels[index]:
        print(f'This was correctly predicted to be a \"{test_labels[index]}\"!')
    else:
        print(f'This was incorrectly predicted to be a \"{np.argmax(prediction[index])}\". It was actually a \"{test_labels[index]}\".')
        return(prediction)

In [28]:
predictor(test_data, test_labels, 149)

This was correctly predicted to be a "1"!
